fix: check to ensure field is defined
TypeError: Cannot read properties of undefined (reading 'qty')
  at <object>.round_floats_in(../../../../../apps/frappe/frappe/public/js/frappe/model/model.js:793:25)
  at erpnext.TransactionControllerconversion_factor(../../../../../apps/erpnext/erpnext/public/js/controllers/transaction.js:1195:17)
  at erpnext.selling.SellingControllerconversion_factor(../../../../../apps/erpnext/erpnext/public/js/utils/sales_common.js:365:11)
  at <anonymous>(../../../../../apps/erpnext/erpnext/public/js/controllers/transaction.js:1254:16)

Signed-off-by: Akhil Narang <me@akhilnarang.dev>