Fix error missing fields on fixtures (#2378)
Only name is currently taken from DB, other fields are mandatory to generate translations:

      File "/Users/pau/frappe-bench/env/lib/python2.7/site-packages/frappe/translate.py", line 407, in get_messages_from_custom_fields
        if cf['fieldtype'] == 'Selection' and cf.get('options'):
    KeyError: u'fieldtype'